name: "Matrix experiment"

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: "py ${{ matrix.python-version }}; dj ${{ matrix.django-version}}"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        django-version:
          - "3.2"
          - "4.0"
      fail-fast: false

    steps:
      - name: "See what we have"
        run: |
          echo "Python: ${{ matrix.python-version }}"
          echo "Django: ${{ matrix.django-version }}"

  # A final step to give a simple name for required status checks.
  # https://github.com/orgs/community/discussions/33579
  success:
    needs: tests
    runs-on: ubuntu-latest
    name: Tests successful
    steps:
      - name: "Success"
        run: |
          echo Tests successful
